apiVersion: apps/v1
kind: Deployment
metadata:
  name: ics-demo
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
      ver: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
        ver: v1
    spec:
      containers:
        - name: ics-container
          image: myanakiev/sb-demo:v2
---
apiVersion: v1
kind: Service
metadata:
  name: ics-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
